spring.application.name=servicio-personas
server.port=9000
otel.traces.exporter=otlp
otel.exporter.otlp.endpoint=http://localhost:4317
otel.exporter.otlp.protocol=grpc
otel.service.name=servicio-personas
#otel.traces.sampler=always_on
#logging.level.io.opentelemetry=DEBUG
#logging.level.io.opentelemetry.exporter=DEBUG
#otel.traces.exporter=logging
#otel.exporter.otlp.logs.endpoint=http://localhost:4317/v1/logs
#otel.logs.exporter=none